### PR TITLE
bpo-12178: Handle escape character

### PR DESCRIPTION
**Pull request by Tapuzi**
Hey.
I noticed a comment in the cpython repository discussing this PR which pointed out a potential bug: https://github.com/python/cpython/pull/13710/files/4c4683677a32232d0900854c41f8d6f057d11869#diff-ff5a6b2bf6c6b916d131c6da1da9360f
It seemed like a small fix, and I implemented it as an exercise and with some hope of contributing a bit.

I will understand if you don't wish to accept this PR for any reason.

### CODE REVIEW

**Comment by berkerpeksag** [comment]
Hello, thank you for your interest to improve Python. Just to clarify, are you referring to Serhiy's comment about unnecessary quoting at https://github.com/python/cpython/pull/13710/files/4c4683677a32232d0900854c41f8d6f057d11869#r289614627 The link in the description goes to the whole `Lib/test/test_csv.py`, so I wanted to be sure I understand the context here.

**Comment by Tapuzi** [comment]
Thank you for already contributing, I love Python.

Yes, you understood me correctly.

Briefly, this patch makes the code not quote escaped characters, as written in the docs.

**Comment by berkerpeksag** [comment]
Nice! I'll review your patch, combine it with my PR, and [attribute you as co-author](https://help.github.com/en/articles/creating-a-commit-with-multiple-authors) with the following details:

```
Co-Authored-By: Tapuzi <anotahacou@gmail.com>
```

Thanks!

**Comment by berkerpeksag** [comment]
@Tapuzi I've now combined your changes into my original PR. Let me know if you want me to change your attribution in the commit message and NEWS entry (e.g. if you prefer using your full name) Thank you!

**Comment by Tapuzi** [comment]
Hey, I will highly appreciate it if you will use my full name.
Thank you very much!

**Comment by berkerpeksag** [comment]
Sure, could you give it in the following format?

```
FirstName LastName <your@email.address>
```

I couldn't find it on your profile.

**Comment by Tapuzi** [comment]
Hey. I didn't notice my name was missing.

Itay Elbirt <anotahacou@gmail.com>

Sorry for the late response.

**Comment by Tapuzi** [comment]
Hey. I didn't realize my name was missing.

```Itay Elbirt <anotahacou@gmail.com>```

Sorry for the late response.

**Comment by berkerpeksag** [comment]
No worries, I've just updated commit message and NEWS entry: https://github.com/python/cpython/pull/13710

**Pull request closed without merging**
